version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: frontend_build
      buildspec: session-app/buildspec-frontend.yml
        
    - identifier: backend_build
      buildspec: connectplatform/buildspec-backend.yml

# This buildspec file serves as an orchestrator that parallelizes the builds
# Individual build configs are in their respective component directories
#
# No phases are defined here as all work is done in the component buildspecs
# No artifacts are defined here as all artifacts are defined in the component buildspecs