version: 0.2

cache:
  paths:
    - session-app/node_modules/**/*

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Using Node.js runtime version 18 and Python 3.11"
      - echo "Setting up AWS CLI configuration"
      - aws --version
      - echo "Creating S3 bucket for Lambda deployments if it doesn't exist"
      - aws s3 mb s3://sessions-red-lambda-deployments --region us-east-1 || true
      - echo "Creating S3 bucket for web app deployments if it doesn't exist"
      - aws s3 mb s3://sessions-red-react-app-deployments --region us-east-1 || true
      - echo "Installing frontend dependencies"
      - cd session-app
      - echo "Cleaning up node_modules if needed"
      - rm -rf node_modules || true
      - npm install
      - cd ..
      - echo "Installing backend dependencies"
      - cd connectplatform
      - pip install -r requirements.txt boto3
      - cd ..

  build:
    commands:
      - echo "Building the React frontend"
      - cd session-app
      - npm run build
      - cd ..
      - echo "Packaging the Lambda function"
      - cd connectplatform
      - echo "Creating deployment package"
      - mkdir -p build
      - cp -r *.py requirements.txt build/
      - pip install -r requirements.txt -t build/
      - cd build
      - zip -r ../lambda-deployment.zip .
      - cd ..
      - echo "Uploading Lambda deployment package to S3"
      - aws s3 cp lambda-deployment.zip s3://sessions-red-lambda-deployments/
      - echo "Processing CloudFormation template"
      - cp template.yml deployment-template.yml
      - cd ..

  post_build:
    commands:
      - echo "Syncing frontend build artifacts to S3"
      - aws s3 sync session-app/build/ s3://sessions-red-react-app-deployments/ --delete --exact-timestamps
      - echo "Deploying backend Lambda functions"
      - cd connectplatform
      - echo "Creating/updating CloudFormation stack"
      - >
        aws cloudformation deploy 
        --template-file deployment-template.yml 
        --stack-name sessions-red-api 
        --parameter-overrides Stage=prod 
        --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND 
        --no-fail-on-empty-changeset 
        --region us-east-1 || true
      - cd ..

artifacts:
  files:
    - "session-app/build/**/*"
    - "connectplatform/deployment-template.yml"
    - "connectplatform/lambda-deployment.zip"
  base-directory: '.'
  discard-paths: no